name: Publish Package to npmjs

on:
  push:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Install
        uses: actions/setup-node@v3
        with:   
          version: 7
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      - name: Test
      - run: pnpm run test
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest]
      fail-fast: false
          
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2.0.1
        name: Install 
        with:
          version: 7
          
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

       name: build
      - run: npm run build
       name: publish
      - run: npm  publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}